### ISSUE TITLE
mo script sends curl to the wrong url

### ISSUE THREAD

**Issue by gianpaj** [10gen/mongo-orchestration#184]
```
$ scripts/mo mongo_orchestration/configurations/servers/clean.json start
DBPATH=/Users/gianfranco/tmp/orchestrations
LOGPATH=/Users/gianfranco/tmp/orchestrations
POST_DATA='{ "id" : "standalone", "name": "mongod", "procParams": { "dbpath": "/Users/gianfranco/tmp/orchestrations", "ipv6": true, "logappend": true, "logpath": "/Users/gianfranco/tmp/orchestrations/mongod.log", "journal": true, "port": 27017 } }'

POST http://localhost:8889/configurations HTTP/1.1 404 Not Found
```

it should do something like:
```
$ curl -XPUT http://localhost:8889/v1/servers/standalone -d@mongo_orchestration/configurations/servers/clean.json
```

**Comment by llvtt** [comment]
I think the problem is that the `mongo_orchestration` package is being included as part of the path to the json. As noted in the readme, `mo` has to be used inside the `mongo_orchestration` package ("in the same directory as 'configurations'"), so invocations have to look like:

    mo configurations/servers/clean.json start

This is actually pretty confusing, IMO. For what it's worth, you can also use `curl` to accomplish the same tasks as `mo` with about the same amount of effort. We should perhaps consider removing `mo` from the mongo-orchestration repo entirely, since I don't think it's used anywhere or by anyone at this point.

**Comment by gianpaj** [comment]
I see. Should I close this in that case?
